ENVIRONMENT_VARIABLE_LOG_LEVEL = "LOG_LEVEL"

class Constants:
    
    #auth
    ID = "id"
    END_POINT = "end_point"
    AUTH_INFO = "auth_info"
    TENANT_ID = "tenant_id"
    APP_ID = "app_id"
    PFX_FILE = "pfx_file"
    AUTHORIZATION = "Authorization"
    BEARER = "Bearer"
    ACCESS_TOKEN = "accessToken"
    CONTENT_TYPE = "content_type"
    TYPE = "type"
    NAME = "name"
    SCENE_ID = "sceneId"
    DESCRIPTION = "description"
    PROPERTIES = "properties"
    BLOB_URL = "blob_url"
    DOWNLOAD_SAS_URL = "download_sas_url"
    UPLOAD_SAS_URL = "upload_sas_url"
    GENERATE_DOWNLOAD_SAS_URL = "generate_download_sas_url"
    RESOLUTION = "resolution"
    WAVELENGTH = "wavelength"
    TYPES = "types"
    ITEMS = "items"
    CONTENT_TYPES = "contentTypes"
    SCENE_DATE = "_date"
    CLOUD_COVER_PERCENTAGE = "CloudCoverPercentage"
    DARK_PIXEL_PERCENTAGE = "DarkPixelPercentage"
    GEOMETRY = "geometry"
    SENSOR_PLACEMENTS = "sensor_placements"
    TSI = "tsi"
    TSI_FQDN = "dataaccess_fqdn"

